name: deploy-staging

on:
  push:
    branches: ['staging']

jobs:
  deploy:
    name: deploy-staging
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_SSH_HOST }}
          username: ${{ secrets.STAGING_SSH_USER }}
          password: ${{ secrets.STAGING_SSH_PASSWORD }}
          script: ${{ secrets.STAGING_SSH_SCRIPT }}
