name: deploy-production

on:
  push:
    branches: ['main']

jobs:
  deploy:
    name: deploy-production
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_SSH_HOST }}
          username: ${{ secrets.PRODUCTION_SSH_USER }}
          password: ${{ secrets.PRODUCTION_SSH_PASSWORD }}
          script: ${{ secrets.PRODUCTION_SSH_SCRIPT }}
